USERMODULES_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/miniutils.c $(USERMODULES_DIR)/st7735/lcd.c $(USERMODULES_DIR)/st7735/st7735_reg.c $(USERMODULES_DIR)/st7735/st7735.c  

CFLAGS_USERMOD += -I$(USERMODULES_DIR)