USERMODULES_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/main.c 
SRC_USERMOD += $(USERMODULES_DIR)/spi_config.c 
SRC_USERMOD += $(USERMODULES_DIR)/lib/lcd.c 
SRC_USERMOD += $(USERMODULES_DIR)/lib/st7735_reg.c 
SRC_USERMOD += $(USERMODULES_DIR)/lib/st7735.c  
SRC_USERMOD += $(USERMODULES_DIR)/lib/yeisonint_logo.c

CFLAGS_USERMOD += -I$(USERMODULES_DIR) -Werror=unused-function
# CFLAGS_EXTRA +=-DHAL_SPI_MODULE_ENABLED=1