USERMODULES_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/miniutils.c 
SRC_USERMOD += $(USERMODULES_DIR)/ministm32h723_board.c 
SRC_USERMOD += $(USERMODULES_DIR)/st7735/lcd.c 
SRC_USERMOD += $(USERMODULES_DIR)/st7735/st7735_reg.c 
SRC_USERMOD += $(USERMODULES_DIR)/st7735/st7735.c  
SRC_USERMOD += $(USERMODULES_DIR)/st7735/logo_160_80.c

CFLAGS_USERMOD += -I$(USERMODULES_DIR) -Werror=unused-function
# CFLAGS_EXTRA +=-DHAL_SPI_MODULE_ENABLED=1