USERMODULES_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/mp_board.c
SRC_USERMOD += $(USERMODULES_DIR)/board.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/camera.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov2640_regs.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov2640.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov5640_regs.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov5640.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov7670_regs.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov7670.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov7725_regs.c
SRC_USERMOD += $(USERMODULES_DIR)/Camera/ov7725.c
SRC_USERMOD += $(USERMODULES_DIR)/ST7735/lcd.c
SRC_USERMOD += $(USERMODULES_DIR)/ST7735/st7735_reg.c
SRC_USERMOD += $(USERMODULES_DIR)/ST7735/st7735.c
SRC_USERMOD += $(USERMODULES_DIR)/ST7735/yeisonint_logo.c
SRC_USERMOD += $(USERMODULES_DIR)/ST7735/yeisonint_logo.c
SRC_USERMOD += $(USERMODULES_DIR)/hw/dcmi.c
SRC_USERMOD += $(USERMODULES_DIR)/hw/dma.c
SRC_USERMOD += $(USERMODULES_DIR)/hw/gpio.c
SRC_USERMOD += $(USERMODULES_DIR)/hw/i2c.c
SRC_USERMOD += $(USERMODULES_DIR)/hw/spi.c
SRC_USERMOD += $(USERMODULES_DIR)/hw/tim.c

CFLAGS_USERMOD += -w -I$(USERMODULES_DIR) -I$(USERMODULES_DIR)/Camera -I$(USERMODULES_DIR)/ST7735/ -I$(USERMODULES_DIR)/hw -DUSE_HAL_DCMI_REGISTER_CALLBACKS=1